POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6Ik1hcmtEb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzE5OTM2MjYsImV4cCI6MTczMTk5NzIyNiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.H0mB02kxISwq8oeS2Y_aM-xcj3y7H0QmxyG3IlOA4Vc
{
    "title": "Wha's new with NestJs when", 
    "postType": "post",
    "slug": "whats-new-with-nestjs-klm",
    "status": "draft",
    "content": "NestJs is a great framework for building scalable and maintainable server-side applications. It provides a set of tools and features that make it easy to build robust and efficient applications. In this post, we'll explore some of the key features and benefits of NestJs and how it can help you build better applications.",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n}",
    "featuredImageUrl": "https://images.unsplash.com/photo-1593720219276-0b1eacd0aef4?q=80&w=2061&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    //"publishOn": "2024-04-02T15:20:15.123Z",
    //"tags": ["nestjs", "javascript", "typescript"],
    "metaOptions": {
        "metaValue": "{\"sidebarEnabled\":true, \"footerActive\":true}"
    },
    "tags":[1, 3]
}