POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6Ik1hcmtEb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzE5ODYzNTQsImV4cCI6MTczMTk4OTk1NCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.uC55ciPtYAa-yqc1ERgnMfXp6NaArC4A33rN1HDa7ys

{
    "firstName": "Mark",
    "lastName": "Doe",
    "email": "MarkDoe@example.com",
    "password": "Password@123"
}


POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6Ik1hcmtEb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzE1NjU2NzgsImV4cCI6MTczMTU2OTI3OCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.X9SI2SS0k-wxtv8ac6JXn6O-yfEvb0QQ7Ls6LfHYwEc

{
    "users": [
        {
            "firstName": "Demian",
            "lastName": "Doe",
            "email": "demian@doe.com",
            "password": "Password@123"
        },
        {
            "firstName": "Tom",
            "lastName": "Doe",
            "email": "tom@doe.com",
            "password": "Password@@123"
        }
    ]
}