POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Mark",
    "lastName": "Doe",
    "email": "MarkDoe@example.com",
    "password": "Password@123"
}


POST http://localhost:3000/users/create-many
Content-Type: application/json

{
    "users": [
        {
            "firstName": "Demian",
            "lastName": "Doe",
            "email": "demian@doe.com",
            "password": "Password@123"
        },
        {
            "firstName": "Tom",
            "lastName": "Doe",
            "email": "tom@doe.com",
            "password": "Password@@123"
        }
    ]
}