POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6Ik1hcmtEb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzIwNzAxMzAsImV4cCI6MTczMjA3MzczMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.HVsVAXyjqPKmXWqzGed0gZ64Sde6RXCAV4VYtAcNslw

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJpYXQiOjE3MzIwNzAxMzAsImV4cCI6MTczMjE1NjUzMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.zzTVTGgEgayvGMOJKcjHVqSiu5Sad4f3dVVw7EmkU_8"
}